global:
  resolve_timeout: 5m

route:
  receiver: 'discord_webhook'
  repeat_interval: 4h
  group_by: [ alertname ]
  group_wait: 1s
  group_interval: 1s


receivers:
  - name: 'discord_webhook'
    webhook_configs:
      - url: 'http://discord-alerts:9094'
        send_resolved: true
