global:
  resolve_timeout: 5m

route:
  receiver: "discord"

receivers:
  - name: "discord"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/DISCORD_WEBHOOK_SECRETE"
        send_resolved: true
