networks:
  app-network:
    driver: bridge

services:
  myapp:
    container_name: didcomm-mediator
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_LOCAL_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    networks:
      - app-network
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
