version: '3.8'

services:

  prometheus: 
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    command: --config.file /etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage: