version: "3.8"
services:
  mediator:
    build:
      context: .
    container_name: didcomm-mediator
    image: ghcr.io/adorsys/didcomm-mediator-rs:latest
    ports:
      - 3000:8080
    env_file:
      - .env
    depends_on:
      - mongodb
    network_mode: host # Use the host's networking stack for the mediator container

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    network_mode: bridge # Keep MongoDB container in the default bridge network

volumes:
  mongo-data: null
