version: "3.8"
services:
  mediator:
    build: 
      context: .
    container_name: didcomm-mediator
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mediator-network
 
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - mediator-network
   
networks:
  mediator-network:
    driver: bridge

volumes:
  mongo-data:
