version: "3.8"

services:
  # DIDComm Mediator Service
  mediator:
    build: 
      context: .
    container_name: didcomm-mediator
    ports:
      - "8080:8080"  # Expose the server port
      - "9100:9100"  # Expose port for Prometheus metrics
    env_file:
      - .env
    depends_on:
      - mongodb
      - prometheus
      - grafana
    networks:
      - mediator-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - mediator-network
    ports:
      - "27018:27017"  # Expose MongoDB port

  # Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"  # Prometheus web interface
    command: --config.file=/etc/prometheus/prometheus.yml # Use Prometheus config file
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus config file
    networks:
      - mediator-network
    restart: unless-stopped

  # Grafana Service with Anonymous Access Enabled
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Expose Grafana web interface on port 3001
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin           # Set admin password
      - GF_AUTH_ANONYMOUS_ENABLED=true              # Enable anonymous access
      - GF_AUTH_ANONYMOUS_ORG_NAME="Main Org."     # Specify organization name for anonymous users
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer           # Set role for anonymous users 
      - GF_AUTH_DISABLE_LOGIN_FORM=true             
    networks:
      - mediator-network
    restart: unless-stopped

networks:
  mediator-network:
    driver: bridge

volumes:
  mongo-data:
