services:
  mediator:
    build: 
      context: .
    container_name: didcomm-mediator
    ports:
      - "8080:8080"
    env_file:
      - .env  # Reference the .env file
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mediator-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env  # Reference the same .env file
    volumes:
      - mongo-data:/data/db
    networks:
      - mediator-network
    healthcheck:  
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "--quiet"]
      interval: 10s  
      timeout: 5s  
      retries: 5  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

networks:
  mediator-network:
    driver: bridge

volumes:
  mongo-data:
