services:
  mediator_server:
    container_name: didcomm-mediator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_LOCAL_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env

volumes:
  mongodb_data:
