global:
  scrape_interval: 15s
scrape_configs:
  - job_name: didcomm-mediator
    static_configs:
      - targets: ['http://localhost:8080/metrics']
  - job_name: mongodb
    static_configs:
      - targets:
          - mongodb:27019
  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100