global:
  scrape_interval: 5s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: didcomm-mediator
    honor_labels: true
    static_configs:
      - targets:
          - host.docker.internal:3000

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100'] 