replicaCount: 1
namespace: didcomm-mediator
externalDnsHostname: didcomm-mediator.eudi-adorsys.com

mongodb:
  databaseName: mongodb
mediator:
  image:
    repository: ghcr.io/adorsys/didcomm-mediator-rs
    pullPolicy: Always
    tag: latest
  ingress:
    tls:
      hosts:
        - "*.eudi-adorsys.com"
    secretName: mediator-secret
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod


mongoVolume:
  persistentVolumeClaim:
    storageSize: 10Gi  

  persistentVolume:
    storageSize: 10Gi  
    pathOnHost: /var/lib/mongodb 


  mountPath: /var/lib/mongodb
