replicaCount: 1
namespace: didcomm-mediator

mongodb:
  databaseName: mongodb

mediator:
  image:
    repository: ghcr.io/adorsys/didcomm-mediator-rs
    pullPolicy: IfNotPresent
    tag: latest

mongoVolume:
  persistentVolumeClaim:
    storageSize: 10Gi  

  persistentVolume:
    storageSize: 10Gi  
    pathOnHost: /var/lib/mongodb 


  mountPath: /var/lib/mongodb

envConfig: 
  MONGO_DBN: mediatorDB
  MONGO_URI: mongodb://mongodb:27017
  SERVER_LOCAL_PORT: "3000"
  SERVER_PUBLIC_DOMAIN: http://alice-mediator.com