[package]
name = "sample-pop-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
default-run = "sample-pop-server"

[dependencies]
axum = { version = "0.6.20" }
chrono = "0.4.26"
hyper = { version = "0.14.27", features = ["full"] }
json-canon = "0.1.3"
serde_json = "1.0.104"
signatory = { version = "0.27.1", features = ["ecdsa", "secp256k1"] }
tempfile = "3.7.1"
tokio = { version = "1.30.0", features = ["full"] }
tower-http = { version = "0.4.3", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["json"] }

[dev-dependencies]
tower = { version = "0.4.13", features = ["util"] }
