[package]
name = "keystore"
version = "0.1.0"
edition = "2021"

[dependencies]
did-utils.workspace = true

chrono.workspace = true
serde_json.workspace = true
thiserror.workspace = true
nix.workspace = true
chacha20poly1305 = "0.10.1"
log = "0.4.22"

