apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-mediator-kube-prometheus-alertmanager
  namespace: didcomm-mediator
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'discord'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: 'discord'
        discord_configs:
          - url_file: '/etc/alertmanager/secrets/mediator-eks-secret/discord-webhook-secret'
            send_resolved: true
            message: '{{ template "discord.default.message" . }}'
    templates:
      - '/etc/alertmanager/configmaps/alertmanager-discord-template/*.tmpl'