apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord-bridge
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: alertmanager-discord-bridge
  ports:
  - protocol: TCP
    port: 9094
    targetPort: 9094