apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.externalSecret.metadata.name }}
spec:
  refreshInterval: {{ .Values.externalSecret.spec.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.spec.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.spec.target.name }}
    creationPolicy: {{ .Values.externalSecret.spec.target.creationPolicy }}
  data:
  - secretKey: {{ .Values.externalSecret.spec.secretKey1 }}
    remoteRef:
      key: {{ .Values.awsSecretName }}
      property: {{ .Values.externalSecret.awssecretKey1 }}
  - secretKey: {{ .Values.externalSecret.spec.secretKey2 }}
    remoteRef:
      key: {{ .Values.awsSecretName }}
      property: {{ .Values.externalSecret.awssecretKey2 }}