apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  labels:
    grafana_dashboard: "1"
data:
  grafana.ini: |
    [server]
    root_url = "https://didcomm-mediator.eudi-adorsys.com/grafana/"
    serve_from_sub_path = true