apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDnsHostname }}
    {{- toYaml .Values.mediator.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.externalDnsHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 3000
  tls:
  - hosts:
    - {{ .Values.externalDnsHostname }}
    secretName: {{ .Values.mediator.ingress.secretName }}
   