apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: didcomm-mediator-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/" # Rewrite paths if necessary
spec:
  ingressClassName: nginx # Specifies the NGINX Ingress Controller
  rules:
  - host: didcomm-mediator.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-mediator-service
            port:
              number: 8080
