apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mediator-service
  annotations: 
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDnsHostname }}  
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.certificateArn }} 
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"   
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-mediator
  ports:
  - name: https
    port: 443
    targetPort: 3000
  type: LoadBalancer
