apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-deployment-pvc
spec:
  storageClassName: "high-performance" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
