apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mediator-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mediator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mediator
    spec:
      containers:
          - name: {{ .Release.Name }}-mediator-container
            image: {{ .Values.mediator.image.repository}}:{{ .Values.mediator.image.tag}}
            imagePullPolicy: {{ .Values.mediator.image.pullPolicy}}
            ports:
              - containerPort: 8080
          - env:
            - name: MONGO_DBN
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DBN
                  name: env
             - name: MONGO_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mongo-password
                    key: password
             - name: MONGO_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-mongo-username
                    key: username
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb:27018"
            - name: SERVER_LOCAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: SERVER_LOCAL_PORT
                  name: env
            - name: SERVER_PUBLIC_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: SERVER_PUBLIC_DOMAIN
                  name: env
            - name: STORAGE_DIRPATH
              valueFrom:
                configMapKeyRef:
                  key: STORAGE_DIRPATH
                  name: env