apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mediator-service-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: mediator-kube-prometheus
spec:
  selector:
    matchLabels:
      app: mediator 
  namespaceSelector:
    matchNames:
      - didcomm-mediator
  endpoints:
  - port: https
    path: /metrics
    interval: 5s