apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.mongoVolume.persistentVolume.storageSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.mongoVolume.persistentVolume.pathOnHost }}