apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          resources: {}
          env:
            - name: MONGO_DBN
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: MONGO_DBN
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-password
                  key: password
          volumeMounts:
            - name: {{ .Release.Name }}-mongo-persistent-storage
              mountPath: {{ .Values.mongoVolume.mountPath }}
      restartPolicy: Always
      volumes:
        - name: {{ .Release.Name }}-mongo-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mongo-pvc
