apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-service-monitor
  namespace: didcomm-mediator
  labels:
    release: mediator-kube-prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
  namespaceSelector:
    matchNames:
      - didcomm-mediator
  endpoints:
  - port: metrics
    interval: 5s