apiVersion: external-secrets.io/v1beta1
kind: SecretStore 
metadata:
  name: mediator-secret-store
  namespace: didcomm-mediator
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1

 