apiVersion: external-secrets.io/v1beta1
kind: SecretStore 
metadata:
  name: mediator-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      # role: arn:aws:iam::982081049921:role/mediator-secrets-role
      service: SecretsManager
      region: eu-central-1

 