[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

