[package]
name = "protocole-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true

plugin-api.workspace = true
tracing.workspace = true
lazy_static.workspace = true
didcomm = { workspace = true, features = ["uniffi"] }
