[package]
name = "did-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json-patch = "1.0.0"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
json-canon = "0.1.3"
