[package]
name = "trust-ping"
version = "0.1.0"
edition = "2021"

[dependencies]
shared.workspace = true
message-api.workspace = true

didcomm.workspace = true
serde.workspace = true
uuid.workspace = true
async-trait.workspace = true
serde_json.workspace = true
thiserror.workspace = true
axum = { workspace = true, features = ["macros"] }

[dev-dependencies]
shared = { workspace = true, features = ["test-utils"] }
tokio = { version = "1.42.0", default-features = false, features = [
    "macros",
    "rt",
] }
