[package]
name = "trust-ping"
version = "0.1.0"
edition = "2021"

[dependencies]
shared.workspace = true

didcomm.workspace = true
serde.workspace = true
uuid.workspace = true
serde_json.workspace = true
thiserror.workspace = true
hyper = { workspace = true, features = ["full"] }
axum = { workspace = true, features = ["macros"] }

[dev-dependencies]
json-canon = "0.1.3"
shared = { workspace = true, features = ["test-utils"] }
tokio = { version = "1.27.0", default-features = false, features = [
    "macros",
    "rt",
] }
