[package]
name = "handler"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true

plugin-api.workspace = true
dotenv-flow.workspace = true
tracing.workspace = true
lazy_static.workspace = true
