name: Load Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run load test with Artillery
        uses: artilleryio/action-cli@v1
        env:
          ARTILLERY_AUTH_TOKEN: ${{ secrets.ARTILLERY_AUTH_TOKEN }}
        with:
          command: "run --output test-report.json load-test.yml"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artillery-test-results
          path: test-report.json

      - name: Comment PR with Test Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `🎯 Load Test Results\n\nTest results have been uploaded as artifacts.`
            })