name: Load Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run load test with Artillery Cloud
        id: run_test
        uses: artilleryio/action-cli@v1
        timeout-minutes: 15
        env:
          ARTILLERY_CLOUD_KEY: ${{ secrets.ARTILLERY_CLOUD_KEY }} 
        with:
          command: run load-test.yml --count 5 --output report.json --record

      - name: Display test result link
        run: |
          echo "View the test results on Artillery Cloud: ${{ steps.run_test.outputs.result_url }}"

      - name: Check test results
        if: failure()
        run: |
          echo "Load test failed. Please check the results."
          exit 1
