name: Load Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run load test with Artillery Cloud
        uses: artilleryio/action-cli@v1
        env:
          ARTILLERY_AUTH_TOKEN: ${{ secrets.ARTILLERY_AUTH_TOKEN }}
        with:
          command: "cloud --output cloud-test.json load-test.yml"
          secrets: inherit

      - name: Get Test Results
        run: |
          echo "Load test completed!"
          echo "View detailed results at: https://cloud.artillery.io/tests/${TEST_ID}"

      - name: Comment PR with Test Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          TEST_ID: ${{ env.TEST_ID }}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `🎯 Load Test Results\n\nView detailed results here: https://cloud.artillery.io/tests/${process.env.TEST_ID}`
            })