name: Rust CI

on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build and Test Did Utils
      run: |
        cd did-utils
        cargo build --verbose
        cargo test --verbose

    - name: Build and Test Sample Pop Server
      run: |
        cd sample-pop-server
        cargo build --verbose
        cargo run --bin didgen
        cargo test --verbose
