name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install Nextest test runner
      uses: taiki-e/install-action@nextest

    - name: Install system dependencies
      run: sudo apt update && sudo apt install -y libssl-dev pkg-config

    - name: Build and Run Test
      run: |
        cargo build --workspace --all-features
        cargo nextest run --workspace --all-features